###
GET http://localhost:8080/api/categories

###
GET http://localhost:8080/api/elements

###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Fruits",
  "title": "A1",
  "password": "123"
}

###
POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Vegetables",
  "title": "A3",
  "password": "456"
}

###
POST http://localhost:8080/api/categories/1/elements
Content-Type: application/json

{
    "name": "orange",
    "price": 100
}

###
POST http://localhost:8080/api/categories/1/elements
Content-Type: application/json

{
    "name": "apple",
    "price": 50
}

###
DELETE http://localhost:8080/api/categories/1

###
PUT http://localhost:8080/api/categories/1
Content-Type: application/json

{
  "name": "TastyFruits",
  "title": "A2"
}

###
PUT http://localhost:8080/api/elements/1
Content-Type: application/json

{
    "name": "Orange",
    "price": 75
}

###
DELETE http://localhost:8080/api/elements/1